version: '3'
services: 
    mongo:
        image: mongo
        container_name: mongo
        hostname: mongo
        command: mongod --bind_ip_all --port 27017
        expose: 
            - '27017'
        ports: 
            - '27017:27017'
        volumes:
            - ./scripts:/scripts